# Generated by Django 2.1.15 on 2022-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MDoctorDetail',
            fields=[
                ('dr_id_autoincrement', models.AutoField(db_column='dr_ID_autoincrement', primary_key=True, serialize=False)),
                ('pk_dr_id', models.UUIDField(db_column='Pk_dr_ID')),
                ('dr_name', models.CharField(max_length=255)),
                ('frequency', models.TimeField(blank=True, null=True)),
                ('addedon', models.DateTimeField()),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('rv', models.TextField(db_column='RV')),
            ],
            options={
                'db_table': 'm_doctor_detail',
                'managed': False,
            },
        ),
    ]
