# Generated by Django 2.1.15 on 2022-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEntityType',
            fields=[
                ('pk_entity_typeid', models.CharField(db_column='Pk_entity_typeID', max_length=36, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'm_entity_type',
                'managed': False,
            },
        ),
    ]
