# Generated by Django 2.1.15 on 2022-02-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0002_mentitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblUserDetail',
            fields=[
                ('pk_userid', models.CharField(db_column='Pk_userID', max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('user_contact', models.BigIntegerField(blank=True, null=True)),
                ('user_password', models.TextField(blank=True, null=True)),
                ('user_email', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'tbl_user_detail',
                'managed': False,
            },
        ),
    ]
